const housesAspects = {
  1: {
    label: "first",
    title: "House of self",
    relatedSign: "aries",
    planet: "mars",
    meaning: [
      "you",
      "appearance",
      "first impressions",
      "ego",
      "sense of self",
      "physical body",
      "identity",
      "early childhood",
    ],
  },
  2: {
    label: "second",
    title: "House of money and Value",
    relatedSign: "taurus",
    planet: "venus",
    meaning: [
      "personal finances",
      "material possessions",
      "income",
      "assets",
      "security",
    ],
  },
  3: {
    label: "third",
    title: "House of communication",
    relatedSign: "gemini",
    planet: "mercury",
    meaning: [
      "communication",
      "siblings",
      "school",
      "short-term trips",
      "neighborhood",
    ],
  },
  4: {
    label: "fourth",
    title: "House of home and family",
    relatedSign: "cancer",
    planet: "moon",
    meaning: [
      "home",
      "property",
      "family",
      "inner world",
      "father figure",
      "your old age",
      "your ancestors",
    ],
  },
  5: {
    label: "fifth",
    title: "House of love",
    relatedSign: "leo",
    planet: "sun",
    meaning: [
      "children",
      "love",
      "romance",
      "dating",
      "sex",
      "fertility",
      "creativity",
      "fun",
      "pleasure",
      "good fortune",
    ],
  },
  6: {
    label: "sixth",
    title: "House of work and health",
    relatedSign: "virgo",
    planet: "mercury",
    meaning: [
      "health",
      "illness",
      "everyday routines",
      "work environment",
      "coworkers",
      "pets",
    ],
  },
  7: {
    label: "seventh",
    title: "House of relationship",
    relatedSign: "libra",
    planet: "venus",
    meaning: [
      "committed relationships (personal & business)",
      "marriage",
      "partnerships",
      "public enemies",
    ],
  },
  8: {
    label: "eighth",
    title: "House of transformation",
    relatedSign: "scorpio",
    planet: "pluto",
    meaning: [
      "transformation",
      "inheritance",
      "taxes",
      "other's people money",
      "shared finance",
      "joint income",
      "power",
      "death",
      "occult abilities",
    ],
  },
  9: {
    label: "ninth",
    title: "House of purpose",
    relatedSign: "sagittarius",
    planet: "jupiter",
    meaning: [
      "higher education",
      "religion",
      "philosophy",
      "faith",
      "law",
      "long-distance / foreign travel",
      "international",
      "god",
      "divine",
    ],
  },
  10: {
    label: "tenth",
    title: "House of career",
    relatedSign: "capricorn",
    planet: "saturn",
    meaning: [
      "carrer",
      "profession",
      "public image",
      "reputation",
      "fame",
      "ambitions",
      "legacy",
    ],
  },
  11: {
    label: "eleventh",
    title: "House of groups",
    relatedSign: "aquarius",
    planet: "uranus",
    meaning: [
      "friends",
      "groups",
      "community",
      "networks",
      "good spirit",
      "hopes and wishes",
      "luck",
    ],
  },
  12: {
    label: "twelfth",
    title: "House of sacrifice",
    relatedSign: "pisces",
    planet: "neptune",
    meaning: [
      "instrospection",
      "institutions",
      "meditation",
      "occultism",
      "collective unconscious",
      "hidden",
      "psychic abilities",
      "limitations",
      "debts of destiny",
      "exile",
      "isolation",
    ],
  },
};

const elements = {
  fire: {
    label: "fire",
    signs: ["aries", "leo", "sagittarius"],
    opposite: "water",
    season: "summer",
    direction: "south",
    tarot: "wands",
    positiveTraits: [
      "courage",
      "enthusiasm",
      "willpower",
      "action",
      "strength",
    ],
    negativeTraits: [
      "anger",
      "jealousy",
      "hatred",
      "pettiness",
      "recklessness",
      "irrationality",
    ],
  },
  earth: {
    label: "earth",
    signs: ["taurus", "virgo", "capricorn"],
    opposite: "air",
    season: "winter",
    direction: "north",
    tarot: "pentacles",
    positiveTraits: [
      "grounded",
      "patience",
      "truth",
      "reliability",
      "thoroughness",
      "stability",
    ],
    negativeTraits: ["dullness", "laziness", "inconsiderate", "gluttony"],
  },
  water: {
    label: "water",
    signs: ["cancer", "escorpio", "piscis"],
    opposite: "fire",
    season: "fall",
    direction: "west",
    tarot: "cups",
    positiveTraits: [
      "compassion",
      "love",
      "flexibility",
      "forgiveness",
      "understanding",
    ],
    negativeTraits: [
      "indifference",
      "inistability",
      "moodiness",
      "depression",
      "fragility",
    ],
  },
  air: {
    label: "air",
    signs: ["gemini", "libra", "aquarius"],
    opposite: "earth",
    season: "spring",
    direction: "east",
    tarot: "swords",
    positiveTraits: [
      "intelligent",
      "practical",
      "optimistic",
      "curious",
      "creativity",
    ],
    negativeTraits: [
      "impulsive",
      "frivolous",
      "gullible",
      "flighty",
      "detached",
    ],
  },
};

const zodiacSignProperties = {
  aries: {
    label: "aries",
    element: "fire",
    polarity: "positive",
    quality: "cardinal",
    planet: ["mars"],
    house: 1,
    reason: "I am",
    color: ["red"],
    gem: ["diamond"],
    matches: ["gemini", "libra", "sagittarius", "taurus"],
    topMatch: ["sagittarius"],
    opposite: "libra",
    traits: ["ambitiuos", "independent", "impatient"],
  },
  taurus: {
    label: "taurus",
    element: "earth",
    polarity: "negative",
    quality: "fixed",
    planet: ["venus"],
    house: 2,
    reason: "I have",
    color: ["pink"],
    gem: ["emerald"],
    matches: ["virgo", "piscis", "capricorn", "cancer"],
    topMatch: ["cancer", "virgo"],
    opposite: "escorpio",
    traits: ["dependable", "musical", "practical"],
  },
  gemini: {
    label: "gemini",
    element: "air",
    polarity: "positive",
    quality: "mutable",
    planet: ["mercury"],
    house: 3,
    reason: "I think",
    color: ["yellow"],
    gem: ["emerald", "tiger's eye"],
    matches: ["aries", "leo", "libra"],
    topMatch: ["aries", "leo"],
    opposite: "sagittarius",
    traits: ["curious", "affectionate", "kind"],
  },
  cancer: {
    label: "cancer",
    element: "water",
    polarity: "negative",
    quality: "cardinal",
    planet: ["moon"],
    house: 4,
    reason: "I feel",
    color: ["yellow"],
    gem: ["ruby", "pearl"],
    matches: ["piscis", "taurus", "scorpio"],
    topMatch: ["piscis", "taurus"],
    opposite: "capricorn",
    traits: ["intuitive", "emotional", "intelligent", "passionate"],
  },
  leo: {
    label: "leo",
    element: "fire",
    polarity: "positive",
    quality: "fixed",
    planet: ["sun"],
    house: 5,
    reason: "I create",
    color: ["gold"],
    gem: ["carnelian"],
    matches: ["libra", "scorpio", "aries", "pisces"],
    topMatch: ["libra"],
    opposite: "aquarius",
    traits: ["proud", "bold", "ambitious"],
  },
  virgo: {
    label: "virgo",
    element: "earth",
    polarity: "negative",
    quality: "mutable",
    planet: ["mercury"],
    house: 6,
    reason: "I examine",
    color: ["silver"],
    gem: ["peridot"],
    matches: ["cancer", "taurus", "capricorn"],
    topMatch: ["cancer"],
    opposite: "piscis",
    traits: ["grateful", "organized", "kind"],
  },
  libra: {
    label: "libra",
    element: "air",
    polarity: "positive",
    quality: "cardinal",
    planet: ["venus"],
    house: 7,
    reason: "I relate",
    color: ["blue"],
    gem: ["sapphire"],
    matches: ["gemini", "leo", "aquarius", "sagittarius"],
    topMatch: ["gemini"],
    opposite: "aries",
    traits: ["diplomatic", "artistic", "intelligent"],
  },
  escorpio: {
    label: "escorpio",
    element: "water",
    polarity: "negative",
    quality: "fixed",
    planet: ["venus"],
    house: 8,
    reason: "I desire",
    color: ["black"],
    gem: ["topaz", "opal"],
    matches: ["gemini", "leo", "aquarius", "sagittarius"],
    topMatch: ["cancer"],
    opposite: "taurus",
    traits: ["diplomatic", "artistic", "intelligent"],
  },
  sagittarius: {
    label: "sagittarius",
    element: "fire",
    polarity: "positive",
    quality: "mutable",
    planet: ["jupiter"],
    house: 9,
    reason: "I understand",
    color: ["light blue"],
    gem: ["topaz"],
    matches: ["aries", "leo", "aquarius"],
    topMatch: ["aries"],
    opposite: "gemini",
    traits: ["adventurous", "creative", "strong", "willed"],
  },
  capricorn: {
    label: "capricorn",
    element: "earth",
    polarity: "negative",
    quality: "cardinal",
    planet: ["saturn"],
    house: 10,
    reason: "I use",
    color: ["dark blue"],
    gem: ["lapiz lazuli"],
    matches: ["virgo", "taurus", "pisces"],
    topMatch: ["virgo"],
    opposite: "cancer",
    traits: ["detail-oriented", "intelligent", "hardworking"],
  },
  aquarius: {
    label: "aquarius",
    element: "air",
    polarity: "positive",
    quality: "fixed",
    planet: ["uranus"],
    house: 11,
    reason: "I know",
    color: ["sky blue"],
    gem: ["amethyst"],
    matches: ["leo", "gemini", "aquarius", "saggitarius"],
    topMatch: ["sagittarius"],
    opposite: "leo",
    traits: ["imaginative", "idealistic", "intuitive"],
  },
  piscis: {
    label: "piscis",
    element: "water",
    polarity: "negative",
    quality: "mutable",
    planet: ["neptune"],
    house: 12,
    reason: "I believe",
    color: ["sea green"],
    gem: ["moonstone"],
    matches: ["virgo", "scorpio", "piscis"],
    topMatch: ["virgo"],
    opposite: "virgo",
    traits: ["imaginative", "idealistic", "intuitive"],
  },
};
